name: Development - Feature Branch Testing

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main
      - 'feature-branch-A'

jobs:
  quick-test:
    name: Quick CI Tests
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  docker-test:
    name: Docker Build Test (No Push)
    needs: [quick-test]
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      push-image: false
