name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature-branch-A'

jobs:
    unit-testing:
        name: Unit Testing
        strategy:
          matrix:
            node-version: [18, 19, 20]
            os: [ubuntu-latest, windows-latest, macos-latest]

            exclude:
              - os: windows-latest
                node-version: 18
        runs-on: ${{ matrix.os }}
        services:
          mongo:
            image: mongo:6.0
            ports:
              - 27017:27017
            options: >-
              --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
              --health-interval=10s
              --health-timeout=5s
              --health-retries=5

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v5

        - name: Setup NodeJS Version - ${{ matrix.node-version }}
          uses: actions/setup-node@v4.4.0
          with:
            node-version: ${{ matrix.node-version }}
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          env:
            MONGO_URI: mongodb://localhost:27017/solar-system-test
          run: npm test