name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature-branch-A'

env:
  MONGO_URI: ${{secrets.MONGO_URI}}
  MONGO_USERNAME: ${{secrets.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
jobs:
    unit-testing:
        name: Unit Testing
        strategy:
          matrix:
            node-version: [18, 19, 20]
            os: [ubuntu-latest, windows-latest, macos-latest]

            exclude:
              - os: windows-latest
                node-version: 18
        runs-on: ${{ matrix.os }}

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v5

        - name: Setup NodeJS Version - ${{ matrix.node-version }}
          uses: actions/setup-node@v4.4.0
          with:
            node-version: ${{ matrix.node-version }}
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          id: Nodejs-unit-testing-step
          run: npm test

        - name: Archive Test Result
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result-${{ matrix.os }}-${{ matrix.node-version }}
            path: test-results.xml
            retention-days: 1

    code-coverage:
      name: Code Coverage
      needs: unit-testing
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v5

        - name: Setup NodeJS
          uses: actions/setup-node@v4.4.0
          with:
            node-version: 18

        - name: Install Dependencies
          run: npm install

        - name: Run Code Coverage
          continue-on-error: true
          run: npm run coverage

        - name: Archive Coverage Report
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: Coverage-Report
            path: coverage/
            retention-days: 1
    docker-build:
      name: Docker Build
      #needs: code-coverage
      permissions:
        packages: write

      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v5

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

        - name: GHCR Login
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and Push Docker Image
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: |
              docker.io/${{ secrets.DOCKER_USERNAME }}/solar-system:latest
              ghcr.io/${{ github.repository_owner }}/solar-system:latest
