name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature-branch-A'

jobs:
    unit-testing:
        name: Unit Testing
        strategy:
          matrix:
            node-version: [18, 19, 20]
            os: [ubuntu-latest, windows-latest, macos-latest]

            exclude:
              - os: windows-latest
                node-version: 18
        runs-on: ${{ matrix.os }}

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v5

        - name: Setup NodeJS Version - ${{ matrix.node-version }}
          uses: actions/setup-node@v4.4.0
          with:
            node-version: ${{ matrix.node-version }}
    
        - name: Start MongoDB
          uses: supercharge/mongodb-github-action@1.12.0
          with:
            mongodb-version: 6.0
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          env:
            MONGO_URI: mongodb://localhost:27017/solar-system-test
          run: npm test